spring:
  thymeleaf:
    cache: false
  http:
    encoding:
      charset: UTF-8
  jackson:
    time-zone: Asia/Shanghai
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: 123456



server:
  port: 8085